#preload = ~/Pictures/japan.jpg
#preload = ~/Pictures/wallpaper1.jpg
#preload = ~/Pictures/face.jpg
#preload = ~/Pictures/purple.jpg
#preload = ~/Pictures/blue.jpg
wallpaper {
    monitor = DP-1
    path = ~/Pictures/irelia.jpg
    fit_mode = cover
}
