format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$character"""

add_newline = true

[directory]
style = "blue"

[character]
success_symbol = "[❯](blue)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"


# Display Git branch name
[git_branch]
format = 'on [$symbol$branch(:$remote_branch)]($style) '
style = 'bold purple'

# Configure Git status with counts for each type of change
[git_status]
#format = "[$conflicted_count$conflicted $untracked_count$untracked $modified_count$modified $staged_count$staged $renamed_count$renamed $deleted_count$deleted $ahead_behind $stashed]($style)"
style = "cyan"
format = '([\[$all_status$ahead_behind\]]($style) )'
