[general]
import = ["~/.config/alacritty/flat.toml"]

[cursor.style]
    shape = "Block"
[cursor.vi_mode_style]
    shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 18

[font.normal]
family = "IosevkaTerm NF"
#family = "JetBrainsMono NF"
style = "normal"

[window]
#opacity = 1 
opacity = 0.85
