import = ["~/.config/alacritty/theme.toml"]
#import = ["~/.config/alacritty/tokyo.toml"]

[cursor.style]
    shape = "Beam"
[cursor.vi_mode_style]
    shape = "Beam"

[env]
TERM = "xterm-256color"

[font]
size = 18

[font.normal]
family = "Iosevka Nerd Font"
style = "semibold"

[window]
  opacity = 0.75
