import = ["~/.config/alacritty/flat.toml"]

[cursor.style]
    shape = "Block"
[cursor.vi_mode_style]
    shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 18

[font.normal]
family = "Iosevka Nerd Font"
style = "light"

[window]
  opacity = 0.75
